[package]
name = "caching-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
once_cell = "1.19.0"
reqwest = "0.12.7"
axum = "0.7.5"
